spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/produtos
    username: admin
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
